# Pandas Data Analysis in Salem Witchcraft

In [1]:
# Library
import pandas as pd

In [2]:
# Read CSV file 
accused = pd.read_csv('Accused-Witches-Data-Set.csv')
anti = pd.read_csv('Anti-Parris-Social-Data-Set.csv')
committee = pd.read_csv('Committee-List-Data-Set.csv')
committee_yearly = pd.read_csv('Committee-Yearly-Data-Set.csv')
pro = pd.read_csv('Pro-Parris-Social-Data-Set.csv')
salem = pd.read_csv('Salem-Village-Data-Set.csv')
tax = pd.read_csv('Tax-Comparison-Data-Set.csv')
towns = pd.read_csv('Towns-Data-Set.csv')

## Accused Witches Data Set

In [3]:
# Read first 5 rows
accused.head()

Accused Witch       Residence   Month of Accusation  \
0         Abbott, Arthur         Ipswich                     5   
1  Abbott, Nehemiah, Jr.       Topsfield                     4   
2            Alden, John          Boston                     5   
3         Andrew, Daniel   Salem Village                     5   
4        Barker, Abigail         Andover                     9   

   Month of Execution  Sort  
0                 NaN     1  
1                 NaN     2  
2                 NaN     3  
3                 NaN     4  
4                 NaN     5

In [4]:
# Read last 5 rows
accused.tail()

Accused Witch       Residence   Month of Accusation  \
147       Wilds, Sarah       Topsfield                     4   
148      Wilford, Ruth       Haverhill                     8   
149      Willard, John   Salem Village                     5   
150  Wilson, Sarah Jr.         Andover                     9   
151  Wilson, Sarah Sr.         Andover                     9   

     Month of Execution  Sort  
147                 7.0   148  
148                 NaN   149  
149                 8.0   150  
150                 NaN   151  
151                 NaN   152

In [5]:
# Rows, Columns
accused.shape

(152, 5)

In [6]:
# Summary Statistics
accused.describe()

Month of Accusation  Month of Execution        Sort
count           152.000000           20.000000  152.000000
mean              6.039474            8.100000   76.500000
std               2.752197            0.967906   44.022721
min              -1.000000            6.000000    1.000000
25%               4.750000            7.000000   38.750000
50%               5.000000            8.000000   76.500000
75%               8.000000            9.000000  114.250000
max              11.000000            9.000000  152.000000

In [7]:
# Names of the columns in dataset
accused.columns

Index(['Accused Witch', ' Residence ', 'Month of Accusation',
       'Month of Execution', 'Sort'],
      dtype='object')

In [8]:
print('Number of accused witches by their residence:')
accused[' Residence '].value_counts()

Number of accused witches by their residence:


 Andover               45
 Salem Town            24
 Salem Village         15
 Gloucester             9
 Reading                7
 Topsfield              6
 Haverhill              6
 Lynn                   5
 Rowley                 5
 Ipswich                4
 Beverly                4
 Billerica              3
 Boxford                3
 Woburn                 3
 Piscataqua, Maine      2
 Boston                 2
 Charlestown            2
 Amesbury               1
 Malden                 1
 Salisbury              1
 Chelmsford             1
 Wells, Maine           1
 Marblehead             1
 Manchester             1
Name:  Residence , dtype: int64

In [9]:
# Reset Index to count total towns
villages = accused[' Residence '].value_counts()
villages = villages.to_frame("Places Accused").reset_index()
villages

index  Places Accused
0              Andover               45
1           Salem Town               24
2        Salem Village               15
3           Gloucester                9
4              Reading                7
5            Topsfield                6
6            Haverhill                6
7                 Lynn                5
8               Rowley                5
9              Ipswich                4
10             Beverly                4
11           Billerica                3
12             Boxford                3
13              Woburn                3
14   Piscataqua, Maine                2
15              Boston                2
16         Charlestown                2
17            Amesbury                1
18              Malden                1
19           Salisbury                1
20          Chelmsford                1
21        Wells, Maine                1
22          Marblehead                1
23          Manchester                1

In [10]:
# Total towns
# Count total towns
villages.index

RangeIndex(start=0, stop=24, step=1)

The town of Andover has the most accustion; however, the last 7 residence have the least accustion. Salem Town and Salem Village is the next has the most accusation. 

In [11]:
print('Number of accused by month of excecution:')
accused['Month of Execution'].value_counts()

Number of accused by month of excecution:


9.0    9
7.0    5
8.0    5
6.0    1
Name: Month of Execution, dtype: int64

In [12]:
print('Number of accused by month:')
accused['Month of Accusation'].value_counts()

Number of accused by month:


 5     39
 9     33
 8     23
 4     22
 7     12
-1      9
 3      4
 11     3
 6      3
 2      3
 10     1
Name: Month of Accusation, dtype: int64

In [13]:
# This is the order of Months of Accusation. 
# -1 indicates that the actual month of accusation is not known
accused.groupby(["Month of Accusation"])["Month of Accusation"].count()

Month of Accusation
-1      9
 2      3
 3      4
 4     22
 5     39
 6      3
 7     12
 8     23
 9     33
 10     1
 11     3
Name: Month of Accusation, dtype: int64

In [14]:
# This is the order of Months of Execution. 
accused.groupby(["Month of Execution"])["Month of Execution"].count()

Month of Execution
6.0    1
7.0    5
8.0    5
9.0    9
Name: Month of Execution, dtype: int64

On month 9 has the most excution and in month 6 has the least excution. However, on month 5  has the most accustion. On the other hand, on month 10 has the least accustion. 

## Anti-Parris Social Data Set

In [15]:
# Read the first 5 rows 
anti.head()

Name           Identification Sex  Sort
0    Porter, Joseph  Young men. 16 years old   M     1
1      Porter, Sam:  Young men. 16 years old   M     2
2     Preston, Jno.  Young men. 16 years old   M     3
3     Porter, Nath.  Young men. 16 years old   M     4
4  Swinnerton, Ben:  Young men. 16 years old   M     5

In [16]:
# Read the last 5 rows 
anti.tail()

Name Identification Sex  Sort
79      Kittel, James    Free-Holder   M    82
80       Porter, Ben:    Free-Holder   M    80
81     Porter, Israel    Free-Holder   M    83
82       Small, Will:    Free-Holder   M    81
83  Swinneron, Jasper    Free-Holder   M    84

In [17]:
# Rows, Columns
anti.shape

(84, 4)

In [18]:
# Counts for each indentification in total
anti['Identification'].value_counts()

Householder                29
Young men. 16 years old    17
[Church] Member            17
Non-Member                 16
Free-Holder                 5
Name: Identification, dtype: int64

In [19]:
# Counts for each toal sex
anti['Sex'].value_counts()

M    57
F    27
Name: Sex, dtype: int64

In [20]:
# This count for male in each indentification
print('Number of Indentification for Male:')
anti['Identification'][anti['Sex']=='M'].value_counts()

Number of Indentification for Male:


Householder                29
Young men. 16 years old    17
[Church] Member             6
Free-Holder                 5
Name: Identification, dtype: int64

In [21]:
# This count for female in each indentification
print('Number of Indentification for Female:')
anti['Identification'][anti['Sex']=='F'].value_counts()

Number of Indentification for Female:


Non-Member         16
[Church] Member    11
Name: Identification, dtype: int64

There are more male in Anti-Parris than female because many of them are young men and 16 years old based on the dataset. Also, all the males were in Householder. Majority of Householder are in Anti-AntiParris; on the other hand, the Free-Holder was the least. Most of th female are Non-Member or Church Member. 

## Committee List Data Set

In [22]:
# First 5 rows
committee.head()

Committee Members Petition         Social    1685    1686    1687  \
0  Putnam, Lt. John [Senr]    Pro-P  Church Member  1685.0  1686.0  1687.0   
1        Walcott, Jonathan    Pro-P    Householder  1685.0     NaN     NaN   
2             Buxton, John   Anti-P    Householder  1685.0     NaN     NaN   
3          Sibley, William      NoS    Householder  1685.0  1686.0     NaN   
4      Putnam, Thomas Junr    Pro-P  Church Member  1685.0  1686.0  1687.0   

     1688    1689  1690  1691  1692  1693    1694    1695    1696    1697  \
0  1688.0  1689.0   NaN   NaN   NaN   NaN     NaN     NaN  1696.0     NaN   
1     NaN     NaN   NaN   NaN   NaN   NaN     NaN     NaN     NaN     NaN   
2     NaN     NaN   NaN   NaN   NaN   NaN     NaN     NaN     NaN  1697.0   
3     NaN     NaN   NaN   NaN   NaN   NaN     NaN     NaN     NaN     NaN   
4     NaN     NaN   NaN   NaN   NaN   NaN  1694.0  1695.0  1696.0  1697.0   

     1698  Sort  
0     NaN     1  
1     NaN     2  
2     NaN     3  
3     NaN     4  
4  1698.0     5

In [23]:
# Last 5 rows
committee.tail()

Committee Members Petition         Social  1685  1686  1687  1688  1689  \
26         Dale, John    Pro-P    Householder   NaN   NaN   NaN   NaN   NaN   
27  Wilknes, Benjamin    Pro-P  Church Member   NaN   NaN   NaN   NaN   NaN   
28      Walcott, John    Pro-P    Householder   NaN   NaN   NaN   NaN   NaN   
29      Nurs, Samuell   Anti-P  Church Member   NaN   NaN   NaN   NaN   NaN   
30    Rayment, Thomas   Anti-P    Householder   NaN   NaN   NaN   NaN   NaN   

    1690  1691  1692  1693  1694  1695    1696    1697    1698  Sort  
26   NaN   NaN   NaN   NaN   NaN   NaN  1696.0     NaN     NaN    27  
27   NaN   NaN   NaN   NaN   NaN   NaN  1696.0     NaN     NaN    28  
28   NaN   NaN   NaN   NaN   NaN   NaN  1696.0     NaN     NaN    29  
29   NaN   NaN   NaN   NaN   NaN   NaN     NaN  1697.0     NaN    30  
30   NaN   NaN   NaN   NaN   NaN   NaN     NaN     NaN  1698.0    31

In [24]:
# Rows, Columns
committee.shape

(31, 18)

In [25]:
# Counts each total petition
committee['Petition'].value_counts()

Anti-P    15
Pro-P     13
NoS        3
Name: Petition, dtype: int64

In [26]:
# Counts each total Social 
committee['Social'].value_counts()

Householder      16
Church Member    14
Freeholder        1
Name: Social, dtype: int64

In [27]:
# Number by each years that are petition
Years = ['1685','1686','1687','1688','1690','1691','1692','1693','1694','1695','1696','1697','1698']
for y in Years:
    print(committee[y].groupby(committee['Petition']).count())

Petition
Anti-P    1
NoS       1
Pro-P     3
Name: 1685, dtype: int64
Petition
Anti-P    1
NoS       1
Pro-P     3
Name: 1686, dtype: int64
Petition
Anti-P    2
NoS       0
Pro-P     3
Name: 1687, dtype: int64
Petition
Anti-P    2
NoS       0
Pro-P     2
Name: 1688, dtype: int64
Petition
Anti-P    2
NoS       0
Pro-P     3
Name: 1690, dtype: int64
Petition
Anti-P    5
NoS       0
Pro-P     0
Name: 1691, dtype: int64
Petition
Anti-P    4
NoS       0
Pro-P     1
Name: 1692, dtype: int64
Petition
Anti-P    4
NoS       1
Pro-P     0
Name: 1693, dtype: int64
Petition
Anti-P    0
NoS       0
Pro-P     5
Name: 1694, dtype: int64
Petition
Anti-P    0
NoS       1
Pro-P     4
Name: 1695, dtype: int64
Petition
Anti-P    0
NoS       0
Pro-P     5
Name: 1696, dtype: int64
Petition
Anti-P    2
NoS       0
Pro-P     3
Name: 1697, dtype: int64
Petition
Anti-P    2
NoS       0
Pro-P     3
Name: 1698, dtype: int64


In 1690, all five people petition for Anti-P. On the other hand, in the year for 1693 and 1695, they all petition for Pro-P.

## Committee Yearly Data Set

In [28]:
# First 5 Rows
committee_yearly.head()

Committee 1685 Petition       Social       Committee 1686  \
0  Putnam, Lt. John [Senr]    Pro-P       Church     Putnam, Lt. John   
1        Walcott, Jonathan    Pro-P  Householder      Sibley, William   
2             Buxton, John   Anti-P  Householder        Flint, Thomas   
3          Sibley, William      NoS  Householder        Tarbill, John   
4      Putnam, Thomas Junr    Pro-P       Church  Putnam, Thomas Junr   

  Petition.1     Social.1         Committee 1687 Petition.2    Social.2  \
0      Pro-P       Church     Putnam, Capt. John      Pro-P      Church   
1        NoS  Householder    Porter, Lt. Isarell     Anti-P  Freeholder   
2      Pro-P       Church  Flint, Ensigne Thomas      Pro-P      Church   
3     Anti-P       Church          Tarbill, John     Anti-P      Church   
4      Pro-P       Church         Putnam, Thomas      Pro-P      Church   

          Committee 1688     ...         Social.10      Committee 1696  \
0     Putnam, Capt. John     ...            Church  Putnam, Capt. John   
1  Flintt, Ensine Thomas     ...       Householder      Putnam, Thomas   
2     Hutchinson, Joseph     ...            Church          Dale, John   
3         Andrew, Danill     ...            Church   Wilknes, Benjamin   
4                    NaN     ...       Householder       Walcott, John   

  Petition.11    Social.11          Committee 1697 Petition.12    Social.12  \
0       Pro-P       Church  Putnam, Nathaniel Liut       Pro-P       Church   
1       Pro-P       Church            Buxton, John      Anti-P  Householder   
2       Pro-P  Householder          Putnam, Thomas       Pro-P       Church   
3       Pro-P       Church        Putnam, Jonathan       Pro-P       Church   
4       Pro-P  Householder           Nurs, Samuell      Anti-P       Church   

       Committee 1698 Petition.13    Social.13  
0     Andrew, Daniell      Anti-P  Householder  
1     Rayment, Thomas      Anti-P  Householder  
2  Goodell, Zach Senr       Pro-P       Church  
3      Putnam, Thomas       Pro-P       Church  
4      Wilkins, Henry       Pro-P       Church  

[5 rows x 42 columns]

In [29]:
# Last 5 rows
committee_yearly.tail()

Committee 1685 Petition       Social       Committee 1686  \
0  Putnam, Lt. John [Senr]    Pro-P       Church     Putnam, Lt. John   
1        Walcott, Jonathan    Pro-P  Householder      Sibley, William   
2             Buxton, John   Anti-P  Householder        Flint, Thomas   
3          Sibley, William      NoS  Householder        Tarbill, John   
4      Putnam, Thomas Junr    Pro-P       Church  Putnam, Thomas Junr   

  Petition.1     Social.1         Committee 1687 Petition.2    Social.2  \
0      Pro-P       Church     Putnam, Capt. John      Pro-P      Church   
1        NoS  Householder    Porter, Lt. Isarell     Anti-P  Freeholder   
2      Pro-P       Church  Flint, Ensigne Thomas      Pro-P      Church   
3     Anti-P       Church          Tarbill, John     Anti-P      Church   
4      Pro-P       Church         Putnam, Thomas      Pro-P      Church   

          Committee 1688     ...         Social.10      Committee 1696  \
0     Putnam, Capt. John     ...            Church  Putnam, Capt. John   
1  Flintt, Ensine Thomas     ...       Householder      Putnam, Thomas   
2     Hutchinson, Joseph     ...            Church          Dale, John   
3         Andrew, Danill     ...            Church   Wilknes, Benjamin   
4                    NaN     ...       Householder       Walcott, John   

  Petition.11    Social.11          Committee 1697 Petition.12    Social.12  \
0       Pro-P       Church  Putnam, Nathaniel Liut       Pro-P       Church   
1       Pro-P       Church            Buxton, John      Anti-P  Householder   
2       Pro-P  Householder          Putnam, Thomas       Pro-P       Church   
3       Pro-P       Church        Putnam, Jonathan       Pro-P       Church   
4       Pro-P  Householder           Nurs, Samuell      Anti-P       Church   

       Committee 1698 Petition.13    Social.13  
0     Andrew, Daniell      Anti-P  Householder  
1     Rayment, Thomas      Anti-P  Householder  
2  Goodell, Zach Senr       Pro-P       Church  
3      Putnam, Thomas       Pro-P       Church  
4      Wilkins, Henry       Pro-P       Church  

[5 rows x 42 columns]

In [30]:
# Rows, Columns
committee_yearly.shape

(5, 42)

In [31]:
# List of columns
committee_yearly.columns

Index(['Committee 1685', 'Petition', 'Social', 'Committee 1686', 'Petition.1',
       'Social.1', 'Committee 1687', 'Petition.2', 'Social.2',
       'Committee 1688', 'Petition.3', 'Social.3', 'Committee 1689',
       'Petition.4', 'Social.4', 'Committee 1690', 'Petition.5', 'Social.5',
       'Committee 1691', 'Petition.6', 'Social.6', 'Committee 1692',
       'Petition.7', 'Social.7', 'Committee 1693', 'Petition.8', 'Social.8',
       'Committee 1694', 'Petition.9', 'Social.9', 'Committee 1695',
       'Petition.10', 'Social.10', 'Committee 1696', 'Petition.11',
       'Social.11', 'Committee 1697', 'Petition.12', 'Social.12',
       'Committee 1698', 'Petition.13', 'Social.13'],
      dtype='object')

In [32]:
# Counts for each columns for each rows
for c in committee_yearly.columns:
    print(committee_yearly[c].value_counts())

Sibley, William            1
Buxton, John               1
Putnam, Lt. John [Senr]    1
Putnam, Thomas Junr        1
Walcott, Jonathan          1
Name: Committee 1685, dtype: int64
Pro-P     3
Anti-P    1
NoS       1
Name: Petition, dtype: int64
Householder    3
Church         2
Name: Social, dtype: int64
Tarbill, John          1
Flint, Thomas          1
Sibley, William        1
Putnam, Thomas Junr    1
Putnam, Lt. John       1
Name: Committee 1686, dtype: int64
Pro-P     3
NoS       1
Anti-P    1
Name: Petition.1, dtype: int64
Church         4
Householder    1
Name: Social.1, dtype: int64
Porter, Lt. Isarell      1
Flint, Ensigne Thomas    1
Tarbill, John            1
Putnam, Capt. John       1
Putnam, Thomas           1
Name: Committee 1687, dtype: int64
Pro-P     3
Anti-P    2
Name: Petition.2, dtype: int64
Church        4
Freeholder    1
Name: Social.2, dtype: int64
Andrew, Danill           1
Flintt, Ensine Thomas    1
Putnam, Capt. John       1
Hutchinson, Joseph       1
Name: Comm

In 1691, all five people petition for Anti-P and they were Householder member. However, in 1694, all the 5 member petition for Pro-P. Also, 4 people was a Church member and 1 person was a Householder member. In 1696, 5 people petition for Pro-5, and three person was a Church Member and 2 was Householder member. People that were Pro-P are more likely to be Church member. 

## Pro Parris Social Data Set

In [33]:
# First 5 Rows
pro.head()

Name Identification Sex  Sort
0   Wilkins, Jane    Householder   F     1
1  Wilkins, Sarah    Householder   F     2
2    Fuller, Mary    Householder   F     3
3   Wilkins, Ruth    Householder   F     4
4  Wilkins, Eliz:    Householder   F     5

In [34]:
# Last 5 rows
pro.tail()

Name Identification Sex  Sort
100  Holton, Abagail  Church-Member   F   101
101     Darlin, Mary  Church-Member   F   102
102   Hadlock, Sarah  Church-Member   F   103
103    Prince, Sarah  Church-Member   F   104
104      Brown, Han:  Church-Member   F   105

In [35]:
# Count total of member in identification
print('Number of signers by identification category:')
pro['Identification'].value_counts()

Number of signers by identification category:


Householder      53
Church-Member    52
Name: Identification, dtype: int64

In [36]:
# # Count total of sex
print('Number of signers by sex:')
pro['Sex'].value_counts()

Number of signers by sex:


M    54
F    51
Name: Sex, dtype: int64

In [37]:
# Count total of male in each group
print('Number of male in identification:')
pro['Identification'][pro['Sex']=='M'].value_counts()

Number of male in identification:


Householder      29
Church-Member    25
Name: Identification, dtype: int64

In [38]:
# Count total of female in each group
print('Number of female in identification:')
pro['Identification'][pro['Sex']=='F'].value_counts()

Number of female in identification:


Church-Member    27
Householder      24
Name: Identification, dtype: int64

There are more Householder than Church-Member and more Male in Pro Parris. Therefore, there more males in Householder compare more females in Church-Member.

## Salem Village DataSet

In [39]:
# First 5 Rows
salem.head()

Name Petition Church to 1696  Sort
0      Abby, Samuel and son    Pro-P         Church     1
1           Alline, william    Pro-P     Non-Church     2
2  Andrew, Daniell and sons   Anti-P     Non-Church     3
3            Barton, Samull      NoS     Non-Church     4
4                Bayly, Tho      NoS     Non-Church     5

In [40]:
# Last 5 rows
salem.tail()

Name Petition Church to 1696  Sort
132              Wilknes, samuell    Pro-P     Non-Church   133
133          Wilknes, Thomas senr   Anti-P         Church   134
134                 Willard, John      NoS     Non-Church   135
135             williams, Richard      NoS     Non-Church   136
136  Willkins, widdow [of] Samll       NoS     Non-Church   137

In [41]:
# Counts total of people in each petition 
print('Number of people by Petition:')
salem['Petition'].value_counts()

Number of people by Petition:


Pro-P     53
NoS       44
Anti-P    40
Name: Petition, dtype: int64

In [42]:
# Count total people are in Church or not
print('Number of people are a Church Membership:')
salem['Church to 1696'].value_counts()

Number of people are a Church Membership:


Non-Church    103
Church         34
Name: Church to 1696, dtype: int64

## Tax Comparison Data Set

In [43]:
# First 5 Rows
tax.head()

Name Petition    1681  1690  1694  1695  1697  1700  \
0      Abby, Samuel and son    Pro-P     NaN   7.0   7.0   7.0   NaN   NaN   
1               Adams, John      NoS   22.50   NaN   NaN   NaN   NaN   NaN   
2             Aires, Nath'l      NoS   24.00   NaN   NaN   NaN   NaN   NaN   
3           Alline, william    Pro-P     NaN   NaN   4.5   8.0  10.5   8.0   
4  Andrew, Daniell and sons   Anti-P  119.25  36.0  26.0  38.0  40.0  44.0   

   Sort  
0     1  
1     2  
2     3  
3     4  
4     5

In [44]:
# Last 5 rows
tax.tail()

Name Petition  1681  1690  1694  1695  1697  \
195                  williams, Richard      NoS   NaN   4.0   3.0   3.0   5.0   
196  Willkins, [ ], widdow [of] Samll       NoS  36.0   4.0   NaN   NaN   NaN   
197                    Woodbery, peter      NoS   2.5   NaN   NaN   NaN   NaN   
198                       Wooden, John      NoS   NaN   NaN   NaN   NaN   NaN   
199                    Woodrow, Joseph      NoS  15.0   NaN   NaN   NaN   NaN   

     1700  Sort  
195   3.0   196  
196   NaN   197  
197   NaN   198  
198   4.0   199  
199   NaN   200

In [45]:
# The Number of total Petition
tax['Petition'].value_counts()

NoS       101
Pro-P      53
Anti-P     46
Name: Petition, dtype: int64

In [46]:
# Value Counts for multi columns
tax[['1681','1690','1694','1695','1697','1700']].apply(pd.Series.value_counts)

1681  1690  1694  1695  1697  1700
2.00     NaN   1.0   NaN   NaN   NaN   NaN
2.25     1.0   NaN   NaN   NaN   NaN   NaN
2.50     1.0   NaN   NaN   NaN   NaN   NaN
3.00     2.0   4.0   2.0   5.0   3.0   1.0
3.25     2.0   NaN   NaN   NaN   NaN   NaN
3.50     NaN   NaN   6.0   4.0   NaN   1.0
4.00     1.0   8.0   4.0   6.0   1.0  18.0
4.25     1.0   NaN   NaN   NaN   NaN   NaN
4.50     NaN   NaN   5.0   2.0   NaN   1.0
4.75     1.0   NaN   NaN   NaN   NaN   NaN
5.00     3.0   8.0   NaN   4.0   7.0   4.0
5.50     NaN   NaN   7.0   1.0   NaN   1.0
6.00     NaN   4.0   1.0   6.0   6.0  13.0
6.25     1.0   NaN   NaN   NaN   NaN   NaN
6.50     1.0   NaN   NaN   NaN   NaN   NaN
7.00     NaN  15.0  18.0  21.0   3.0   3.0
7.50     1.0   NaN   NaN   NaN   NaN   1.0
8.00     NaN  11.0   7.0   4.0   6.0   6.0
9.00     1.0   NaN  10.0   9.0   3.0   8.0
9.75     1.0   NaN   NaN   NaN   NaN   NaN
10.00    4.0   2.0   4.0   5.0   9.0   7.0
10.50    NaN   NaN   6.0   2.0   2.0   NaN
11.00    NaN   1.0   NaN   NaN   4.0   3.0
12.00    1.0   5.0   NaN   5.0  12.0   8.0
13.00    3.0   1.0   2.0   NaN   1.0   5.0
14.00    NaN   2.0   6.0   5.0   3.0   4.0
15.00    1.0   6.0   1.0   2.0   4.0   2.0
15.50    NaN   NaN   NaN   NaN   1.0   NaN
16.00    1.0   6.0   5.0   3.0   5.0   2.0
17.00    NaN   NaN   1.0   1.0   1.0   NaN
...      ...   ...   ...   ...   ...   ...
42.00    1.0   NaN   NaN   NaN   NaN   NaN
42.50    1.0   NaN   NaN   NaN   NaN   NaN
44.00    NaN   NaN   1.0   1.0   NaN   1.0
45.00    2.0   NaN   NaN   NaN   NaN   NaN
46.00    NaN   NaN   NaN   NaN   NaN   2.0
48.00    2.0   NaN   NaN   NaN   NaN   NaN
49.50    1.0   NaN   NaN   NaN   NaN   NaN
50.00    NaN   1.0   NaN   NaN   2.0   NaN
52.00    NaN   NaN   1.0   NaN   NaN   NaN
52.50    1.0   NaN   NaN   NaN   NaN   NaN
54.00    4.0   NaN   NaN   NaN   1.0   NaN
56.75    1.0   NaN   NaN   NaN   NaN   NaN
58.00    NaN   NaN   NaN   1.0   NaN   NaN
60.00    4.0   NaN   NaN   NaN   NaN   NaN
61.50    1.0   NaN   NaN   NaN   NaN   NaN
66.00    2.0   NaN   NaN   NaN   NaN   NaN
70.50    1.0   NaN   NaN   NaN   NaN   NaN
72.00    1.0   NaN   NaN   NaN   NaN   NaN
75.00    1.0   NaN   NaN   NaN   1.0   NaN
90.00    1.0   NaN   NaN   NaN   NaN   NaN
96.00    1.0   NaN   NaN   NaN   NaN   NaN
102.00   1.0   NaN   NaN   NaN   NaN   NaN
119.25   1.0   NaN   NaN   NaN   NaN   NaN
123.00   1.0   NaN   NaN   NaN   NaN   NaN
132.25   1.0   NaN   NaN   NaN   NaN   NaN
147.00   1.0   NaN   NaN   NaN   NaN   NaN
160.00   1.0   NaN   NaN   NaN   NaN   NaN
166.00   1.0   NaN   NaN   NaN   NaN   NaN
190.00   1.0   NaN   NaN   NaN   NaN   NaN
206.25   1.0   NaN   NaN   NaN   NaN   NaN

[88 rows x 6 columns]

In [47]:
# Too many NaN, so fill it up with 0
result = tax[['1681','1690','1694','1695','1697','1700']].apply(pd.value_counts).fillna(0)
result

1681  1690  1694  1695  1697  1700
2.00     0.0   1.0   0.0   0.0   0.0   0.0
2.25     1.0   0.0   0.0   0.0   0.0   0.0
2.50     1.0   0.0   0.0   0.0   0.0   0.0
3.00     2.0   4.0   2.0   5.0   3.0   1.0
3.25     2.0   0.0   0.0   0.0   0.0   0.0
3.50     0.0   0.0   6.0   4.0   0.0   1.0
4.00     1.0   8.0   4.0   6.0   1.0  18.0
4.25     1.0   0.0   0.0   0.0   0.0   0.0
4.50     0.0   0.0   5.0   2.0   0.0   1.0
4.75     1.0   0.0   0.0   0.0   0.0   0.0
5.00     3.0   8.0   0.0   4.0   7.0   4.0
5.50     0.0   0.0   7.0   1.0   0.0   1.0
6.00     0.0   4.0   1.0   6.0   6.0  13.0
6.25     1.0   0.0   0.0   0.0   0.0   0.0
6.50     1.0   0.0   0.0   0.0   0.0   0.0
7.00     0.0  15.0  18.0  21.0   3.0   3.0
7.50     1.0   0.0   0.0   0.0   0.0   1.0
8.00     0.0  11.0   7.0   4.0   6.0   6.0
9.00     1.0   0.0  10.0   9.0   3.0   8.0
9.75     1.0   0.0   0.0   0.0   0.0   0.0
10.00    4.0   2.0   4.0   5.0   9.0   7.0
10.50    0.0   0.0   6.0   2.0   2.0   0.0
11.00    0.0   1.0   0.0   0.0   4.0   3.0
12.00    1.0   5.0   0.0   5.0  12.0   8.0
13.00    3.0   1.0   2.0   0.0   1.0   5.0
14.00    0.0   2.0   6.0   5.0   3.0   4.0
15.00    1.0   6.0   1.0   2.0   4.0   2.0
15.50    0.0   0.0   0.0   0.0   1.0   0.0
16.00    1.0   6.0   5.0   3.0   5.0   2.0
17.00    0.0   0.0   1.0   1.0   1.0   0.0
...      ...   ...   ...   ...   ...   ...
42.00    1.0   0.0   0.0   0.0   0.0   0.0
42.50    1.0   0.0   0.0   0.0   0.0   0.0
44.00    0.0   0.0   1.0   1.0   0.0   1.0
45.00    2.0   0.0   0.0   0.0   0.0   0.0
46.00    0.0   0.0   0.0   0.0   0.0   2.0
48.00    2.0   0.0   0.0   0.0   0.0   0.0
49.50    1.0   0.0   0.0   0.0   0.0   0.0
50.00    0.0   1.0   0.0   0.0   2.0   0.0
52.00    0.0   0.0   1.0   0.0   0.0   0.0
52.50    1.0   0.0   0.0   0.0   0.0   0.0
54.00    4.0   0.0   0.0   0.0   1.0   0.0
56.75    1.0   0.0   0.0   0.0   0.0   0.0
58.00    0.0   0.0   0.0   1.0   0.0   0.0
60.00    4.0   0.0   0.0   0.0   0.0   0.0
61.50    1.0   0.0   0.0   0.0   0.0   0.0
66.00    2.0   0.0   0.0   0.0   0.0   0.0
70.50    1.0   0.0   0.0   0.0   0.0   0.0
72.00    1.0   0.0   0.0   0.0   0.0   0.0
75.00    1.0   0.0   0.0   0.0   1.0   0.0
90.00    1.0   0.0   0.0   0.0   0.0   0.0
96.00    1.0   0.0   0.0   0.0   0.0   0.0
102.00   1.0   0.0   0.0   0.0   0.0   0.0
119.25   1.0   0.0   0.0   0.0   0.0   0.0
123.00   1.0   0.0   0.0   0.0   0.0   0.0
132.25   1.0   0.0   0.0   0.0   0.0   0.0
147.00   1.0   0.0   0.0   0.0   0.0   0.0
160.00   1.0   0.0   0.0   0.0   0.0   0.0
166.00   1.0   0.0   0.0   0.0   0.0   0.0
190.00   1.0   0.0   0.0   0.0   0.0   0.0
206.25   1.0   0.0   0.0   0.0   0.0   0.0

[88 rows x 6 columns]

In [48]:
# Each person in what petition
print('List of Name in certain petition:')
pd.crosstab(tax['Name'], tax['Petition'])

List of Name in certain petition:


Petition                    Anti-P  NoS  Pro-P
Name                                          
Abby, Samuel and son             0    0      1
Adams, John                      0    1      0
Aires, Nath'l                    0    1      0
Alline, william                  0    0      1
Andrew, Daniell and sons         1    0      0
Barton, Samull                   0    1      0
Bayly, Tho                       0    1      0
Beele, William                   0    1      0
Bishop, David                    1    0      0
Bishop, Edward Junr              0    0      1
Bishop, Edward senr & son        1    0      0
Bishop, Samuell                  1    0      0
Boys, Joseph                     0    1      0
Braybrook, samuell               1    0      0
Brown, Henry                     0    0      1
Brown, John                      0    1      0
Buckly, william junr             1    0      0
Burroughs, John                  0    1      0
Buxton, John Junr                1    0      0
Buxton, John and sons            1    0      0
Carrell, Joseph                  0    1      0
Carrell, Nathaniell              0    1      0
Cave, Thomas                     0    1      0
Chever, Ezekill                  0    0      1
Clark, Thomas                    0    1      0
Cloys, peter                     0    1      0
Cooks, Isaac                     0    1      0
Cory, Gilles                     0    1      0
Cuby, Elisha                     0    1      0
Cummings, Thomas                 0    1      0
...                            ...  ...    ...
osburn, Allexander               1    0      0
phillips, walter                 0    1      0
pope, Joseph                     1    0      0
porter, Isarell                  1    0      0
porter, samuell                  1    0      0
prescott, peter                  0    0      1
preston, Thomas & son            1    0      0
preston, [ ], Widdow & son       1    0      0
prince, James                    0    0      1
putnam, Benjamin                 0    0      1
putnam, Edward                   0    0      1
putnam, Eliazer                  0    0      1
putnam, John Tirtius [III]       0    0      1
putnam, John junr                0    0      1
putnam, Jonathan                 0    0      1
putnam, Joseph                   1    0      0
putnam, Liuet Nathaniell         0    0      1
putnam, Thomas                   0    0      1
sibly, samuell                   0    0      1
smale, william                   1    0      0
smith, Abraham                   1    0      0
smith, samuell & Farme           0    1      0
stacy, Benjamin                  0    0      1
swinerton, Jasper                1    0      0
swinerton, Job and son           1    0      0
swinerton, Joseph                1    0      0
upton, samuell                   1    0      0
upton, william                   1    0      0
wiet, George                     0    1      0
williams, Richard                0    1      0

[200 rows x 3 columns]

In [49]:
# tax[['1681','1690','1694','1695','1697','1700']].sum(axis=1)
# This shows when each person paid their taxes and how much total taxes they paid
tax['Total'] = tax.iloc[:,2:8].sum(axis=1)
tax

Name Petition    1681  1690  1694  1695  \
0                 Abby, Samuel and son    Pro-P     NaN   7.0   7.0   7.0   
1                          Adams, John      NoS   22.50   NaN   NaN   NaN   
2                        Aires, Nath'l      NoS   24.00   NaN   NaN   NaN   
3                      Alline, william    Pro-P     NaN   NaN   4.5   8.0   
4             Andrew, Daniell and sons   Anti-P  119.25  36.0  26.0  38.0   
5                       Barton, Samull      NoS     NaN   4.0   NaN   NaN   
6                           Bayly, Tho      NoS   13.00   NaN   NaN   NaN   
7                       Beele, William      NoS     NaN   6.0   NaN   NaN   
8                        Bishop, David   Anti-P     NaN   NaN   NaN   NaN   
9                  Bishop, Edward Junr    Pro-P     NaN   NaN   7.0   7.0   
10           Bishop, Edward senr & son   Anti-P   48.00  14.0   7.0  10.0   
11                     Bishop, Samuell   Anti-P     NaN   NaN   NaN   NaN   
12                        Boys, Joseph      NoS    3.25   NaN   NaN   NaN   
13                  Braybrook, samuell   Anti-P   16.00   6.0   7.0   7.0   
14                        Brown, Henry    Pro-P     NaN   NaN  10.5  10.5   
15                         Brown, John      NoS   61.50   NaN   NaN   NaN   
16               buckly, william & son   Anti-P   24.00   7.0   5.5   6.0   
17                Buckly, william junr   Anti-P     NaN   NaN   NaN   NaN   
18                     Burroughs, John      NoS   30.00   NaN   NaN   NaN   
19               Buxton, John and sons   Anti-P   75.00  27.0  23.0  24.0   
20                   Buxton, John Junr   Anti-P     NaN   NaN   NaN   NaN   
21                     Carrell, Joseph      NoS     NaN   NaN   NaN   NaN   
22                 Carrell, Nathaniell      NoS     NaN   NaN   NaN   NaN   
23                        Cave, Thomas      NoS    3.00   NaN   NaN   NaN   
24                     Chever, Ezekill    Pro-P   13.00  10.0  10.5  10.0   
25                       Clark, Thomas      NoS   13.00   NaN   NaN   NaN   
26                        Cloys, peter      NoS   28.50  12.0   NaN   NaN   
27                        Cooks, Isaac      NoS    4.25   NaN   NaN   NaN   
28                        Cory, Gilles      NoS    4.00   NaN   NaN   NaN   
29                        Cuby, Elisha      NoS    3.25   NaN   NaN   NaN   
..                                 ...      ...     ...   ...   ...   ...   
170                    Tayler, william      NoS     NaN   3.0   NaN   NaN   
171                      Trask, Samull      NoS     NaN   5.0   NaN   NaN   
172                         Tree, John      NoS     NaN   NaN   4.0   4.0   
173                   Trumball, Joseph      NoS     NaN   3.0   NaN   NaN   
174                     upton, samuell   Anti-P     NaN   4.0   9.0   9.0   
175                     upton, william   Anti-P     NaN   4.0   9.0   9.0   
176                   Walcott, Abraham    Pro-P    9.00   8.0   7.0   7.0   
177             Walcott, Capt Jonathan    Pro-P   66.00  21.0  16.0  12.0   
178                      Walcott, John    Pro-P     NaN  16.0   7.0   7.0   
179             Walcott, Jonathan Junr    Pro-P     NaN   NaN   4.5   4.5   
180                     Walcott, Widow      NoS     NaN   NaN   NaN   NaN   
181                      Watts, Jerimy      NoS    5.00   NaN   NaN   NaN   
182                         Way, Aaron    Pro-P   39.00   8.0  10.5  10.0   
183                       Way, William    Pro-P   30.00  13.0  10.0   8.0   
184                    Whipple, Joseph    Pro-P     NaN   NaN  10.0  10.0   
185                   White, Zachariah      NoS     NaN   NaN   NaN   NaN   
186                       wiet, George      NoS     NaN   NaN   NaN   NaN   
187                       Wilden, John    Pro-P     NaN  16.0   7.0   5.0   
188                  Wilknes, Benjamin    Pro-P   36.00  16.0  13.0  12.0   
189                      Wilknes, Bray    Pro-P   52.50   8.0   5.5   5.0   
190                     Wilkne

In [50]:
# Sum of total each rows in Years
tax[['1681','1690','1694','1695','1697','1700']].sum(axis=1)

0       21.00
1       22.50
2       24.00
3       31.00
4      303.25
5        4.00
6       22.50
7        6.00
8        4.00
9       34.00
10     106.00
11       4.00
12       3.25
13      54.00
14      51.50
15      61.50
16      45.50
17      11.00
18      30.00
19     207.00
20       9.00
21      12.00
22      11.00
23       3.00
24      68.50
25      13.00
26      40.50
27       4.25
28       4.00
29       3.25
        ...  
170      3.00
171      5.00
172     13.00
173      3.00
174     31.00
175     43.00
176     31.00
177    130.00
178     52.00
179      9.00
180     12.00
181      5.00
182     67.50
183     61.00
184     49.00
185      6.00
186     10.00
187     28.00
188    103.00
189     89.00
190     85.00
191     48.00
192     15.50
193    146.75
194      7.00
195     18.00
196     40.00
197      2.50
198      4.00
199     15.00
Length: 200, dtype: float64

In [51]:
# Total of tax by each person
print('List of Total Tax Paid:')
tax.sort_values('Total', ascending=False)

List of Total Tax Paid:


Name Petition    1681  1690  1694  1695  1697  \
119      Porter, Joseph and sons   Anti-P  123.00  50.0  52.0  58.0  75.0   
135     putnam, Liuet Nathaniell    Pro-P  190.00  40.0  38.0  40.0  54.0   
127            Putnam, Capt John    Pro-P  160.00  40.0  30.0  30.0  40.0   
4       Andrew, Daniell and sons   Anti-P  119.25  36.0  26.0  38.0  40.0   
85       Hutchinson, Joseph senr   Anti-P  132.25  40.0  23.0  23.0  31.0   
43         Flint, ensigne Thomas    Pro-P  102.00  29.0  24.0  22.0  39.0   
117                 pope, Joseph   Anti-P   60.00  35.0  34.0  36.0  50.0   
144             Rea, Joshua senr   Anti-P  147.00  25.0  16.0  12.0  16.0   
134               putnam, Joseph   Anti-P     NaN  34.0  44.0  44.0  50.0   
54           Fuller, Thomas senr   Anti-P  166.00   8.0   5.5   5.0  12.0   
19         Buxton, John and sons   Anti-P   75.00  27.0  23.0  24.0  32.0   
136         Putnam, Luet: Thomas      NoS  206.25   NaN   NaN   NaN   NaN   
141                 Rea, Daniell      NoS   60.00  24.5  24.0  24.0  32.0   
166       swinerton, Job and son   Anti-P   90.00  20.0  24.0  24.0  32.0   
133             putnam, Jonathan    Pro-P   36.00  23.0  26.0  26.0  33.0   
73    Herrick, Joseph senr & son   Anti-P   60.00  14.0  22.0  22.0  30.0   
131            putnam, John junr    Pro-P   54.00  20.0  22.0  20.0  28.0   
65     Goodell, Zach: senr & son    Pro-P   54.00  25.0  18.0  20.0  28.0   
88   Ingersoll, Liuet Nathaniell    Pro-P   72.00  20.0  17.0  17.0  20.0   
128               putnam, Edward    Pro-P   37.00  20.0  20.0  20.0  28.0   
193         Wilknes, Thomas senr   Anti-P   56.75  23.0  14.0  14.0  20.0   
138               putnam, Thomas    Pro-P   54.00  20.0  18.0  18.0  24.0   
53           Fuller, Thomas Junr    Pro-P   48.00  25.0  18.0  18.0  18.0   
115           osburn, Allexander   Anti-P   42.00  18.0  15.0  15.0  20.0   
140              Rayment, Thomas   Anti-P   54.00   8.0  16.0  16.0  22.0   
177       Walcott, Capt Jonathan    Pro-P   66.00  21.0  16.0  12.0  15.0   
169                Tarbill, John   Anti-P   24.00  15.0  14.0  16.0  24.0   
153              Sibley, William      NoS   96.00  18.0   NaN   NaN   NaN   
111        Nurs, samuell and son   Anti-P   24.00  15.0  13.0  16.0  22.0   
126             putnam, Benjamin    Pro-P     NaN  20.0  18.0  18.0  24.0   
..                           ...      ...     ...   ...   ...   ...   ...   
102          Mackintire, Phillip      NoS     NaN   NaN   NaN   NaN   NaN   
98                    Lane, John      NoS     NaN   5.0   NaN   NaN   NaN   
152             Sheldon, william      NoS     NaN   5.0   NaN   NaN   NaN   
51                  Fuller, John      NoS     NaN   NaN   NaN   NaN   NaN   
149                Roots, Joseph      NoS    4.75   NaN   NaN   NaN   NaN   
27                  Cooks, Isaac      NoS    4.25   NaN   NaN   NaN   NaN   
33               Darling, Thomas      NoS     NaN   NaN   NaN   NaN   NaN   
72             Hayward, Nickloas      NoS     NaN   NaN   NaN   NaN   NaN   
8                  Bishop, David   Anti-P     NaN   NaN   NaN   NaN   NaN   
11               Bishop, Samuell   Anti-P     NaN   NaN   NaN   NaN   NaN   
95                 Kenye, Thomas      NoS     NaN   NaN   NaN   NaN   NaN   
113          Nurse, Samuell Junr   Anti-P     NaN   NaN   NaN   NaN   NaN   
5                 Barton, Samull      NoS     NaN   4.0   NaN   NaN   NaN   
198                 Wooden, John      NoS     NaN   NaN   NaN   NaN   NaN   
60              Goodell, Abraham      NoS     NaN   NaN   NaN   NaN   NaN   
147             Richerson, David      NoS     NaN   NaN   NaN   NaN   NaN   
157              Smith, Benjemin      NoS     NaN   NaN   NaN   NaN   NaN   
28                  Cory, Gilles      NoS    4.00   NaN   NaN   NaN   NaN   
160               Smith, Solomen      NoS     NaN   NaN   NaN   NaN   NaN   
162              Starns, Charles      NoS     NaN   4.0   NaN   NaN   NaN   
163           Sweneton, 

In [52]:
# List of the top 5 person paid the most taxes in order
print('The top 5 tax payers:')
print(tax.sort_values('Total', ascending=False)[0:5])

The top 5 tax payers:
                         Name Petition    1681  1690  1694  1695  1697  1700  \
119   Porter, Joseph and sons   Anti-P  123.00  50.0  52.0  58.0  75.0  46.0   
135  putnam, Liuet Nathaniell    Pro-P  190.00  40.0  38.0  40.0  54.0  30.0   
127         Putnam, Capt John    Pro-P  160.00  40.0  30.0  30.0  40.0  29.0   
4    Andrew, Daniell and sons   Anti-P  119.25  36.0  26.0  38.0  40.0  44.0   
85    Hutchinson, Joseph senr   Anti-P  132.25  40.0  23.0  23.0  31.0  26.0   

     Sort   Total  
119   120  404.00  
135   136  392.00  
127   128  329.00  
4       5  303.25  
85     86  275.25  


In [53]:
# Average people paid in tax
tax['Total'].mean()

54.0025

In [54]:
# Summary Statistics for Tax in Total
tax['Total'].describe()

count    200.000000
mean      54.002500
std       71.537889
min        2.250000
25%        8.375000
50%       30.000000
75%       61.000000
max      404.000000
Name: Total, dtype: float64

## Towns Data Set

In [55]:
# First 5 Rows
towns.head()

Bin   Amesbury   Andover  Beverly  Billerica  Boston  Boxford  Charlestown  \
0 -1.0         4.0        9      4.0        5.0     5.0      8.0          5.0   
1  1.0         NaN        8      4.0        5.0     5.0      8.0          5.0   
2  2.0         NaN        8      5.0        5.0     NaN      8.0          NaN   
3  3.0         NaN        8      6.0        NaN     NaN      NaN          NaN   
4  4.0         NaN        8      NaN        NaN     NaN      NaN          NaN   

   Chelmsford  Gloucester   ...    Marblehead  Piscataqua, Maine  Reading  \
0        -1.0        -1.0   ...           5.0                9.0      5.0   
1         NaN         9.0   ...           NaN               -1.0      9.0   
2         NaN        11.0   ...           NaN                NaN      4.0   
3         NaN        11.0   ...           NaN                NaN      5.0   
4         NaN         9.0   ...           NaN                NaN      9.0   

   Rowley  Salem Town  Salem Village  Salisbury  Topsfield  Wells, Maine  \
0     8.0         4.0            5.0        6.0        4.0           4.0   
1     8.0         7.0            4.0        NaN        4.0           NaN   
2     8.0         9.0            4.0        NaN        4.0           NaN   
3     8.0         5.0            4.0        NaN        4.0           NaN   
4     8.0         9.0            5.0        NaN        4.0           NaN   

   Woburn  
0     5.0  
1     5.0  
2     5.0  
3     NaN  
4     NaN  

[5 rows x 25 columns]

In [56]:
# Last 5 rows
towns.tail()

Bin   Amesbury   Andover  Beverly  Billerica  Boston  Boxford  \
40  NaN         NaN        9      NaN        NaN     NaN      NaN   
41  NaN         NaN        9      NaN        NaN     NaN      NaN   
42  NaN         NaN        9      NaN        NaN     NaN      NaN   
43  NaN         NaN        9      NaN        NaN     NaN      NaN   
44  NaN         NaN        9      NaN        NaN     NaN      NaN   

    Charlestown  Chelmsford  Gloucester   ...    Marblehead  \
40          NaN         NaN         NaN   ...           NaN   
41          NaN         NaN         NaN   ...           NaN   
42          NaN         NaN         NaN   ...           NaN   
43          NaN         NaN         NaN   ...           NaN   
44          NaN         NaN         NaN   ...           NaN   

    Piscataqua, Maine  Reading  Rowley  Salem Town  Salem Village  Salisbury  \
40                NaN      NaN     NaN         NaN            NaN        NaN   
41                NaN      NaN     NaN         NaN            NaN        NaN   
42                NaN      NaN     NaN         NaN            NaN        NaN   
43                NaN      NaN     NaN         NaN            NaN        NaN   
44                NaN      NaN     NaN         NaN            NaN        NaN   

    Topsfield  Wells, Maine  Woburn  
40        NaN           NaN     NaN  
41        NaN           NaN     NaN  
42        NaN           NaN     NaN  
43        NaN           NaN     NaN  
44        NaN           NaN     NaN  

[5 rows x 25 columns]

In [57]:
# Number of months in certain month
towns['Bin'].value_counts()

 12.0    1
 11.0    1
 10.0    1
 9.0     1
 8.0     1
 7.0     1
 6.0     1
 5.0     1
 4.0     1
 3.0     1
 2.0     1
 1.0     1
-1.0     1
Name: Bin, dtype: int64

In [58]:
# List of the columns' name
towns.columns

Index(['Bin', ' Amesbury ', 'Andover', 'Beverly', 'Billerica', 'Boston',
       'Boxford', 'Charlestown', 'Chelmsford', 'Gloucester', 'Haverhill',
       'Ipswich', 'Lynn', 'Malden', 'Manchester', 'Marblehead',
       'Piscataqua, Maine', 'Reading', 'Rowley', 'Salem Town', 'Salem Village',
       'Salisbury', 'Topsfield', 'Wells, Maine', 'Woburn'],
      dtype='object')

In [59]:
# Number of months of accusation in each towns
for t in towns.columns:
    print(towns[t].value_counts())

 12.0    1
 11.0    1
 10.0    1
 9.0     1
 8.0     1
 7.0     1
 6.0     1
 5.0     1
 4.0     1
 3.0     1
 2.0     1
 1.0     1
-1.0     1
Name: Bin, dtype: int64
4.0    1
Name:  Amesbury , dtype: int64
 9    22
 8    12
 7     7
-1     3
 5     1
Name: Andover, dtype: int64
4.0    2
6.0    1
5.0    1
Name: Beverly, dtype: int64
5.0    3
Name: Billerica, dtype: int64
5.0    2
Name: Boston, dtype: int64
8.0    3
Name: Boxford, dtype: int64
5.0    2
Name: Charlestown, dtype: int64
-1.0    1
Name: Chelmsford, dtype: int64
 11.0    3
 9.0     3
-1.0     3
Name: Gloucester, dtype: int64
8.0    3
7.0    3
Name: Haverhill, dtype: int64
 5.0    2
-1.0    1
 3.0    1
Name: Ipswich, dtype: int64
5.0     3
6.0     1
10.0    1
Name: Lynn, dtype: int64
5.0    1
Name: Malden, dtype: int64
9.0    1
Name: Manchester, dtype: int64
5.0    1
Name: Marblehead, dtype: int64
-1.0    1
 9.0    1
Name: Piscataqua, Maine, dtype: int64
9.0    3
5.0    3
4.0    1
Name: Reading, dtype: int64
8.0    5
Name: Ro

In [60]:
# Total accusation in each towns
for t in towns.columns:
    print(t, towns[t].count())

Bin 13
 Amesbury  1
Andover 45
Beverly 4
Billerica 3
Boston 2
Boxford 3
Charlestown 2
Chelmsford 1
Gloucester 9
Haverhill 6
Ipswich 4
Lynn 5
Malden 1
Manchester 1
Marblehead 1
Piscataqua, Maine 2
Reading 7
Rowley 5
Salem Town 23
Salem Village 16
Salisbury 1
Topsfield 6
Wells, Maine 1
Woburn 3


In [61]:
# Organized with sort values with town's name
for t, count in sorted(((towns[t].count(), t) for t in set(towns.columns)), reverse=True):
    print('%s (%s)' % (t, count))

45 (Andover)
23 (Salem Town)
16 (Salem Village)
13 (Bin)
9 (Gloucester)
7 (Reading)
6 (Topsfield)
6 (Haverhill)
5 (Rowley)
5 (Lynn)
4 (Ipswich)
4 (Beverly)
3 (Woburn)
3 (Boxford)
3 (Billerica)
2 (Piscataqua, Maine)
2 (Charlestown)
2 (Boston)
1 (Wells, Maine)
1 (Salisbury)
1 (Marblehead)
1 (Manchester)
1 (Malden)
1 (Chelmsford)
1 ( Amesbury )


The highest town that had most accusation was Andover. Next, Salem Town and Salem Village had the most accusation. On the other hand, 6 towns had the least accusation.